CREATE TABLE artist (
 id SERIAL PRIMARY KEY NOT NULL,
 name VARCHAR(50) NOT NULL,
 role INT NOT NULL,
 tgId VARCHAR(50) NOT NULL
);

CREATE TABLE tasks(
 id SERIAL PRIMARY KEY NOT NULL,
 priority INTEGER NOT NULL,
 executor INTEGER NOT NULL,
 description VARCHAR(500) NOT NULL,
 project INT NOT NULL,
 scene VARCHAR(50) NOT NULL,
 status INTEGER NOT NULL,
 shot VARCHAR(50) NOT NULL
);

CREATE TABLE projects(
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(1000)
);